#!/usr/bin/env python3
"""
Checkpoint Manager Utilities

Provides functions for generating and parsing checkpoint YAML data
for GitHub Issue workflow Compact resilience.
"""

import json
import sys
from datetime import datetime, timezone


def generate_checkpoint(
    issue_data: dict,
    todowrite_mapping: list,
    todowrite_snapshot: list = None,
    explore_results: dict = None
) -> str:
    """
    Generate checkpoint YAML from Issue data and TodoWrite mapping.

    Args:
        issue_data: Parsed Issue data from issue-parser
        todowrite_mapping: Task mapping from issue-todowrite-sync
        todowrite_snapshot: Optional TodoWrite state for Compact recovery (v1.1)
        explore_results: Optional Phase 2 Explore results (v1.1)

    Returns:
        YAML-formatted checkpoint string
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Extract phases
    phases = issue_data.get("phases", [])
    current_phase = phases[0] if phases else "Phase 1"
    phases_remaining = phases[1:] if len(phases) > 1 else []

    # Count tasks
    total_tasks = len(todowrite_mapping)
    completed_tasks = sum(1 for t in todowrite_mapping if t.get("status") == "completed")
    current_phase_tasks = [t for t in todowrite_mapping if t.get("phase") == current_phase]
    current_phase_completed = sum(1 for t in current_phase_tasks if t.get("status") == "completed")

    # Build checkpoint
    checkpoint = f"""# Issue #{issue_data['issue_number']} Checkpoint
# Generated by checkpoint-manager skill
# Last updated: {now}

issue_number: {issue_data['issue_number']}
issue_title: "{issue_data.get('title', 'Untitled')}"
issue_url: "{issue_data.get('url', '')}"
repo: "{issue_data.get('repo', '')}"

# Phase Tracking
current_phase: "{current_phase}"
phases_completed: []
phases_remaining:
{_format_list(phases_remaining)}

# Task Mapping (TodoWrite ↔ GitHub)
task_mapping:
{_format_task_mapping(todowrite_mapping)}

# Phase 1.5 Results (Parallel Groups) - Updated after dependency analysis
parallel_groups: []

# Progress Statistics
progress:
  current_phase_completed: {current_phase_completed}
  current_phase_total: {len(current_phase_tasks)}
  overall_completed: {completed_tasks}
  overall_total: {total_tasks}
  percentage: {(completed_tasks / total_tasks * 100) if total_tasks > 0 else 0:.1f}

# Timestamps
created_at: "{now}"
last_updated: "{now}"
last_github_sync: "{now}"

# Configuration
auto_close_enabled: {str(issue_data.get('auto_close', True)).lower()}
recovery_hint: "Start with first pending task in {current_phase}"

# Schema Version (for backward compatibility)
schema_version: "1.1.0"
"""

    # Add TodoWrite Snapshot (v1.1)
    if todowrite_snapshot:
        checkpoint += _format_todowrite_snapshot(todowrite_snapshot)

    # Add Recovery Command (v1.1)
    checkpoint += '\n# Recovery Command\nrecovery_command: "/gh:start  # Auto-recovers from checkpoint"\n'

    # Add Explore Results (v1.1)
    if explore_results:
        checkpoint += _format_explore_results(explore_results)

    # Add Execution Stats placeholder (v1.1)
    checkpoint += """
# Execution Stats
execution_stats:
  phase_1_5_duration_ms: 0
  parallel_groups_count: 0
  estimated_speedup_percent: 0
"""

    return checkpoint


def _format_list(items: list) -> str:
    """Format list items as YAML."""
    if not items:
        return "  []"
    return "\n".join(f'  - "{item}"' for item in items)


def _format_todowrite_snapshot(snapshot: list) -> str:
    """Format TodoWrite snapshot as YAML (v1.1)."""
    if not snapshot:
        return ""

    lines = ["\n# TodoWrite Snapshot (Compact recovery)", "todowrite_snapshot:"]
    for item in snapshot:
        lines.append(f"  - index: {item.get('index', 0)}")
        lines.append(f'    content: "{item.get("content", "")}"')
        lines.append(f"    status: {item.get('status', 'pending')}")
        lines.append(f'    activeForm: "{item.get("activeForm", "")}"')
    return "\n".join(lines) + "\n"


def _format_explore_results(results: dict) -> str:
    """Format Phase 2 Explore results as YAML (v1.1)."""
    if not results:
        return ""

    lines = ["\n# Phase 2 Explore Results", "explore_results:"]
    for domain, data in results.items():
        lines.append(f"  {domain}:")
        patterns = data.get("patterns", [])
        lines.append(f"    patterns: {patterns}")
        files = data.get("files", [])
        lines.append(f"    files: {files}")
        rec = data.get("recommendations", "")
        lines.append(f'    recommendations: "{rec}"')
    return "\n".join(lines) + "\n"


def _format_task_mapping(mapping: list) -> str:
    """Format task mapping as YAML."""
    if not mapping:
        return "  []"

    lines = []
    for task in mapping:
        lines.append(f"""  - todowrite_index: {task.get('todowrite_index', 0)}
    github_task_id: {task.get('github_task_id', 0)}
    text: "{task.get('text', '')}"
    phase: "{task.get('phase', 'Phase 1')}"
    status: {task.get('status', 'pending')}""")
    return "\n".join(lines)


def update_task_status(checkpoint_yaml: str, task_index: int, new_status: str) -> str:
    """
    Update a task's status in checkpoint YAML.

    Args:
        checkpoint_yaml: Current checkpoint YAML string
        task_index: TodoWrite index of task to update
        new_status: New status (pending, in_progress, completed)

    Returns:
        Updated YAML string
    """
    # Simple line-by-line update
    lines = checkpoint_yaml.split("\n")
    in_task = False
    target_found = False

    for i, line in enumerate(lines):
        if f"todowrite_index: {task_index}" in line:
            in_task = True
            target_found = True
        elif in_task and "status:" in line:
            lines[i] = f"    status: {new_status}"
            in_task = False
        elif in_task and "todowrite_index:" in line:
            in_task = False

    # Update progress and timestamp
    if target_found:
        lines = _update_progress(lines)
        lines = _update_timestamp(lines)

    return "\n".join(lines)


def update_parallel_groups(checkpoint_yaml: str, groups: list) -> str:
    """
    Update parallel groups in checkpoint YAML.

    Args:
        checkpoint_yaml: Current checkpoint YAML string
        groups: List of parallel group dictionaries

    Returns:
        Updated YAML string
    """
    lines = checkpoint_yaml.split("\n")

    # Find and replace parallel_groups section
    start_idx = None
    end_idx = None

    for i, line in enumerate(lines):
        if line.startswith("parallel_groups:"):
            start_idx = i
        elif start_idx is not None and not line.startswith(" ") and line.strip():
            end_idx = i
            break

    if start_idx is not None:
        if end_idx is None:
            end_idx = len(lines)

        # Build new parallel_groups section
        new_section = ["parallel_groups:"]
        for group in groups:
            new_section.append(f"  - group_id: {group.get('group_id', 0)}")
            new_section.append(f"    mode: {group.get('mode', 'sequential')}")
            new_section.append(f"    tasks: {group.get('tasks', [])}")
            if group.get('reason'):
                new_section.append(f'    reason: "{group.get("reason")}"')

        lines = lines[:start_idx] + new_section + lines[end_idx:]

    lines = _update_timestamp(lines)
    return "\n".join(lines)


def _update_progress(lines: list) -> list:
    """Recalculate and update progress statistics."""
    # Count completed tasks
    completed = sum(1 for line in lines if "status: completed" in line)
    total = sum(1 for line in lines if "todowrite_index:" in line)

    for i, line in enumerate(lines):
        if "overall_completed:" in line:
            lines[i] = f"  overall_completed: {completed}"
        elif "percentage:" in line:
            pct = (completed / total * 100) if total > 0 else 0
            lines[i] = f"  percentage: {pct:.1f}"

    return lines


def _update_timestamp(lines: list) -> list:
    """Update last_updated timestamp."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    for i, line in enumerate(lines):
        if "last_updated:" in line:
            lines[i] = f'last_updated: "{now}"'
            break

    return lines


def parse_checkpoint(checkpoint_yaml: str) -> dict:
    """
    Parse checkpoint YAML into dictionary.
    Simple parser for checkpoint format.

    Args:
        checkpoint_yaml: Checkpoint YAML string

    Returns:
        Dictionary with checkpoint data
    """
    result = {
        "issue_number": 0,
        "issue_title": "",
        "current_phase": "",
        "task_mapping": [],
        "parallel_groups": [],
        "progress": {},
        # v1.1 fields
        "schema_version": "1.0.0",
        "todowrite_snapshot": [],
        "recovery_command": "",
        "explore_results": {},
        "execution_stats": {}
    }

    lines = checkpoint_yaml.split("\n")

    for line in lines:
        line = line.strip()
        if line.startswith("issue_number:"):
            result["issue_number"] = int(line.split(":")[1].strip())
        elif line.startswith("issue_title:"):
            result["issue_title"] = line.split(":", 1)[1].strip().strip('"')
        elif line.startswith("current_phase:"):
            result["current_phase"] = line.split(":", 1)[1].strip().strip('"')
        elif line.startswith("overall_completed:"):
            result["progress"]["overall_completed"] = int(line.split(":")[1].strip())
        elif line.startswith("overall_total:"):
            result["progress"]["overall_total"] = int(line.split(":")[1].strip())
        elif line.startswith("percentage:"):
            result["progress"]["percentage"] = float(line.split(":")[1].strip())
        # v1.1 fields
        elif line.startswith("schema_version:"):
            result["schema_version"] = line.split(":", 1)[1].strip().strip('"')
        elif line.startswith("recovery_command:"):
            result["recovery_command"] = line.split(":", 1)[1].strip().strip('"')

    return result


def update_explore_results(checkpoint_yaml: str, explore_results: dict) -> str:
    """
    Update or add explore_results in checkpoint YAML (v1.1).

    Args:
        checkpoint_yaml: Current checkpoint YAML string
        explore_results: Dict with backend/database/frontend results

    Returns:
        Updated YAML string
    """
    lines = checkpoint_yaml.split("\n")

    # Find existing explore_results section
    start_idx = None
    end_idx = None

    for i, line in enumerate(lines):
        if line.startswith("explore_results:"):
            start_idx = i
        elif start_idx is not None and not line.startswith(" ") and line.strip() and not line.startswith("#"):
            end_idx = i
            break

    # Build new section
    new_section = _format_explore_results(explore_results).strip().split("\n")

    if start_idx is not None:
        if end_idx is None:
            end_idx = len(lines)
        lines = lines[:start_idx] + new_section + lines[end_idx:]
    else:
        # Append at end
        lines.extend([""] + new_section)

    lines = _update_timestamp(lines)
    return "\n".join(lines)


def update_execution_stats(checkpoint_yaml: str, stats: dict) -> str:
    """
    Update execution_stats in checkpoint YAML (v1.1).

    Args:
        checkpoint_yaml: Current checkpoint YAML string
        stats: Dict with phase_1_5_duration_ms, parallel_groups_count, estimated_speedup_percent

    Returns:
        Updated YAML string
    """
    lines = checkpoint_yaml.split("\n")

    for i, line in enumerate(lines):
        if "phase_1_5_duration_ms:" in line:
            lines[i] = f"  phase_1_5_duration_ms: {stats.get('phase_1_5_duration_ms', 0)}"
        elif "parallel_groups_count:" in line:
            lines[i] = f"  parallel_groups_count: {stats.get('parallel_groups_count', 0)}"
        elif "estimated_speedup_percent:" in line:
            lines[i] = f"  estimated_speedup_percent: {stats.get('estimated_speedup_percent', 0)}"

    lines = _update_timestamp(lines)
    return "\n".join(lines)


if __name__ == "__main__":
    # Read JSON input from stdin
    if len(sys.argv) > 1:
        command = sys.argv[1]

        if command == "generate":
            input_data = json.load(sys.stdin)
            issue_data = input_data.get("issue_data", {})
            mapping = input_data.get("todowrite_mapping", [])
            print(generate_checkpoint(issue_data, mapping))

        elif command == "update_task":
            input_data = json.load(sys.stdin)
            checkpoint = input_data.get("checkpoint", "")
            task_index = input_data.get("task_index", 0)
            new_status = input_data.get("new_status", "completed")
            print(update_task_status(checkpoint, task_index, new_status))

        elif command == "update_groups":
            input_data = json.load(sys.stdin)
            checkpoint = input_data.get("checkpoint", "")
            groups = input_data.get("groups", [])
            print(update_parallel_groups(checkpoint, groups))

        elif command == "parse":
            checkpoint = sys.stdin.read()
            print(json.dumps(parse_checkpoint(checkpoint)))

        # v1.1 commands
        elif command == "update_explore":
            input_data = json.load(sys.stdin)
            checkpoint = input_data.get("checkpoint", "")
            explore_results = input_data.get("explore_results", {})
            print(update_explore_results(checkpoint, explore_results))

        elif command == "update_stats":
            input_data = json.load(sys.stdin)
            checkpoint = input_data.get("checkpoint", "")
            stats = input_data.get("stats", {})
            print(update_execution_stats(checkpoint, stats))

        else:
            print(f"Unknown command: {command}", file=sys.stderr)
            sys.exit(1)
    else:
        print("Usage: checkpoint_utils.py <command>", file=sys.stderr)
        print("Commands: generate, update_task, update_groups, parse, update_explore, update_stats", file=sys.stderr)
        sys.exit(1)
